version: "3.8"

services:
    order-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: order-service
        ports:
            - "8083:8083"
        environment:
            - PORT=8083
            - MONGODB_URI=mongodb://ordsrv:ordpass@mongodb:27017/orderdb?authSource=orderdb
            - JWT_SECRET=${JWT_SECRET}
            - SERVICE_SECRET=${SERVICE_SECRET}
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
            - USER_SERVICE_URL=http://user-service:8081
            - PRODUCT_SERVICE_URL=http://product-service:8082
            - NOTIFICATION_SERVICE_URL=http://notification-service:8085
        depends_on:
            mongodb:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            - ecommerce-network
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:8083/health",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    mongodb:
        image: mongo:4.4
        container_name: mongodb
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin123
        volumes:
            - mongodb_data:/data/db
            - ../mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        command: --auth
        networks:
            - ecommerce-network
        healthcheck:
            test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFINITIONS_FILE=/etc/rabbitmq/definitions.json
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - ../rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
        networks:
            - ecommerce-network
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "check_running"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

volumes:
    mongodb_data:
    rabbitmq_data:

networks:
    ecommerce-network:
        driver: bridge
