apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongodb
    namespace: ecommerce
    labels:
        app: mongodb
        component: database
    annotations:
        description: "MongoDB Deployment"
        version: "6.0"
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongodb
    template:
        metadata:
            labels:
                app: mongodb
                component: database
        spec:
            containers:
                - name: mongodb
                  image: mongo:6.0
                  ports:
                      - containerPort: 27017
                  env:
                      - name: MONGO_INITDB_ROOT_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: mongodb-root-username
                      - name: MONGO_INITDB_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mongodb-secret
                                key: mongodb-root-password
                  volumeMounts:
                      - name: mongodb-data
                        mountPath: /data/db
                      - name: mongodb-init
                        mountPath: /docker-entrypoint-initdb.d
                  resources:
                      requests:
                          memory: "512Mi"
                          cpu: "250m"
                      limits:
                          memory: "1Gi"
                          cpu: "500m"
                  livenessProbe:
                      tcpSocket:
                          port: 27017
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      tcpSocket:
                          port: 27017
                      initialDelaySeconds: 5
                      periodSeconds: 5
            volumes:
                - name: mongodb-data
                  persistentVolumeClaim:
                      claimName: mongodb-pvc
                - name: mongodb-init
                  configMap:
                      name: mongodb-init
