apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodb-pvc
    namespace: ecommerce
    labels:
        app: mongodb
        component: database
    annotations:
        description: "MongoDB Persistent Volume Claim"
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: standard
