apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    namespace: ecommerce
    labels:
        app: mongodb
        component: database
    annotations:
        description: "MongoDB credentials"
type: Opaque
data:
    # Root credentials
    mongodb-root-username: cm9vdA== # root
    mongodb-root-password: cGFzc3dvcmQ= # password

    # Service-specific credentials
    user-service-username: dXNlcnNydg== # usersrv
    user-service-password: dXNlcnBhc3M= # userpass

    product-service-username: cHJvZHNydg== # prodsrv
    product-service-password: cHJvZHBhc3M= # prodpass

    order-service-username: b3JkcnNydg== # ordsrv
    order-service-password: b3JkcGFzcw== # ordpass

    payment-service-username: cGF5c3J2 # paysrv
    payment-service-password: cGF5cGFzcw== # paypass

    notification-service-username: bm90c3J2 # notsrv
    notification-service-password: bm90cGFzcw== # notpass
