apiVersion: v1
kind: Service
metadata:
    name: mongodb
    namespace: ecommerce
    labels:
        app: mongodb
        component: database
    annotations:
        description: "MongoDB Service"
        version: "6.0"
spec:
    selector:
        app: mongodb
    ports:
        - port: 27017
          targetPort: 27017
    type: ClusterIP
