apiVersion: apps/v1
kind: Deployment
metadata:
    name: payment-service
    namespace: ecommerce
    labels:
        app: payment-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payment-service
    template:
        metadata:
            labels:
                app: payment-service
        spec:
            containers:
                - name: payment-service
                  image: payment-service:1.0
                  imagePullPolicy: Never # For local Minikube development
                  ports:
                      - containerPort: 8084
                  env:
                      - name: NODE_ENV
                        value: "development"
                      - name: PORT
                        value: "8084"
                      - name: MONGODB_URI
                        value: "mongodb://paysrv:paypass@mongodb:27017/payment-service?authSource=admin"
                      - name: JWT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: payment-service-secrets
                                key: jwt-secret
                      - name: SERVICE_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: payment-service-secrets
                                key: service-secret
                      - name: RABBITMQ_URL
                        value: "amqp://rabbitmq:5672"
                      - name: USER_SERVICE_URL
                        value: "http://user-service:8081"
                      - name: ORDER_SERVICE_URL
                        value: "http://order-service:8083"
                      - name: NOTIFICATION_SERVICE_URL
                        value: "http://notification-service:8085"
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "200m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 8084
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 8084
                      initialDelaySeconds: 5
                      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: payment-service
spec:
    selector:
        app: payment-service
    ports:
        - port: 8084
          targetPort: 8084
    type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
    name: payment-service-secrets
type: Opaque
data:
    mongo-uri: bW9uZ29kYjovL21vbmdvOjI3MDE3L3BheW1lbnQtc2VydmljZQ== # mongodb://mongo:27017/payment-service
    jwt-secret: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl # your_jwt_secret_key_here
    rabbitmq-url: YW1xcDovL3JhYmJpdG1xOjU2NzI= # amqp://rabbitmq:5672
