version: "3"

services:
    payment-service:
        build: .
        ports:
            - "8084:8084"
        environment:
            - PORT=8084
            - MONGODB_URI=mongodb://mongo:27017/payment-service
            - NODE_ENV=development
            - JWT_SECRET=your_jwt_secret_key_here
            - RABBITMQ_URL=amqp://rabbitmq:5672
            - ORDER_SERVICE_URL=http://order-service:8083
            - NOTIFICATION_SERVICE_URL=http://notification-service:5004
        depends_on:
            - mongo
            - rabbitmq
        networks:
            - ecommerce-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules

    mongo:
        image: mongo:6
        ports:
            - "27018:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - ecommerce-network

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - ecommerce-network

networks:
    ecommerce-network:
        driver: bridge

volumes:
    mongo-data:
