version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - "5672:5672" # AMQP protocol port
            - "15672:15672" # Management UI
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin123
        volumes:
            - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
            - ./definitions.json:/etc/rabbitmq/definitions.json:ro
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - rabbitmq_network
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "check_running"]
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    rabbitmq_data:

networks:
    rabbitmq_network:
        driver: bridge
